<?php require_once 'functions.php'; require_once 'employee_signature.php'; require_module_access('employee', 'full');
$id = (int) ($_GET['id'] ?? 0); $employee = mysqli_fetch_assoc(mysqli_query($mysqli, "SELECT * FROM employees WHERE id = $id"));
if (!$employee) { $_SESSION['flash_error'] = 'Karyawan tidak ditemukan.'; header('Location: employees_list.php'); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name = trim($_POST['name'] ?? ''); $level = trim($_POST['employee_level'] ?? '');
    if ($name === '' || $level === '') { $_SESSION['flash_error'] = 'Nama dan level karyawan wajib diisi.'; }
    else { try { $signaturePath = save_employee_signature($employee['employee_no'], $_FILES['signature_file'] ?? [], trim($_POST['signature_data'] ?? ''), $employee['signature_path'] ?? ''); if (!empty($_POST['remove_signature'])) { delete_employee_signature($signaturePath); $signaturePath = ''; } $stmt = mysqli_prepare($mysqli, 'UPDATE employees SET name = ?, employee_level = ?, signature_path = ? WHERE id = ?'); mysqli_stmt_bind_param($stmt, 'sssi', $name, $level, $signaturePath, $id); if (mysqli_stmt_execute($stmt)) { $_SESSION['flash_success'] = 'Data karyawan berhasil diperbarui.'; header('Location: employees_list.php'); exit; } throw new Exception('Data karyawan gagal diperbarui.'); } catch (Throwable $e) { $_SESSION['flash_error'] = $e->getMessage(); } }
    $employee['name'] = $name; $employee['employee_level'] = $level;
}
$error = $_SESSION['flash_error'] ?? ''; unset($_SESSION['flash_error']); include 'header.php';
?>
<div class="container-fluid py-4"><h3 class="mb-3">Edit Karyawan</h3><div class="card card-warning"><div class="card-header"><h3 class="card-title">Data <?= htmlspecialchars($employee['employee_no']) ?></h3></div><form method="post" enctype="multipart/form-data"><div class="card-body">
<?php if ($error): ?><div class="alert alert-danger"><?= htmlspecialchars($error) ?></div><?php endif; ?>
<div class="form-group"><label>Nomor Karyawan</label><input class="form-control" readonly value="<?= htmlspecialchars($employee['employee_no']) ?>"></div>
<div class="form-group"><label for="name">Nama Karyawan</label><input id="name" name="name" class="form-control" required value="<?= htmlspecialchars($employee['name']) ?>"></div>
<div class="form-group"><label for="employee_level">Level / Jabatan</label><input id="employee_level" name="employee_level" class="form-control" required value="<?= htmlspecialchars($employee['employee_level']) ?>"></div>
<div class="form-group"><label for="signature_file">Upload Tanda Tangan PNG</label><input id="signature_file" name="signature_file" type="file" accept="image/png" class="form-control-file"><small class="form-text text-muted">Maksimal 2 MB. Drawing akan diprioritaskan jika diisi.</small></div>
<?php if (!empty($employee['signature_path'])): ?><div class="form-group"><label>Tanda Tangan Saat Ini</label><div><img src="<?= htmlspecialchars($employee['signature_path']) ?>" alt="Tanda tangan" style="max-width:300px;max-height:100px;border:1px solid #ddd;background:#fff"></div><div class="custom-control custom-checkbox mt-2"><input class="custom-control-input" type="checkbox" name="remove_signature" id="remove_signature"><label class="custom-control-label" for="remove_signature">Hapus tanda tangan saat ini</label></div></div><?php endif; ?>
<div class="form-group"><label>Gambar Tanda Tangan Baru</label><div class="border rounded bg-light p-2" style="max-width:620px"><canvas id="signature-canvas" width="600" height="220" style="width:100%;height:auto;background:#fff;touch-action:none;cursor:crosshair"></canvas></div><input type="hidden" name="signature_data" id="signature_data"><button type="button" id="clear-signature" class="btn btn-sm btn-outline-secondary mt-2"><i class="fas fa-eraser mr-1"></i>Bersihkan Drawing</button></div>
</div><div class="card-footer"><a href="employees_list.php" class="btn btn-secondary">Batal</a><button class="btn btn-warning" type="submit"><i class="fas fa-save mr-1"></i>Perbarui Karyawan</button></div></form></div></div>
<?php include 'footer.php'; ?>
<script>
document.addEventListener('DOMContentLoaded', function () { const canvas=document.getElementById('signature-canvas'),ctx=canvas.getContext('2d'),output=document.getElementById('signature_data'); let drawing=false,hasDrawing=false; ctx.strokeStyle='#000';ctx.lineWidth=2.5;ctx.lineCap='round';ctx.lineJoin='round'; function point(e){const r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*canvas.width/r.width,y:(t.clientY-r.top)*canvas.height/r.height};} function start(e){e.preventDefault();drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);} function move(e){if(!drawing)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();hasDrawing=true;} function end(){drawing=false;if(hasDrawing)output.value=canvas.toDataURL('image/png');} canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',end);canvas.addEventListener('mouseleave',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end);document.getElementById('clear-signature').addEventListener('click',function(){ctx.clearRect(0,0,canvas.width,canvas.height);output.value='';hasDrawing=false;}); });
</script>
